(TeX-add-style-hook "serie2-solutions"
 (lambda ()
    (TeX-run-style-hooks
     "tabularx"
     "ccicons"
     "scale=2"
     "scrtime"
     "hyperref"
     "float"
     "verbatim"
     "amsfonts"
     "amsmath"
     "fontenc"
     "T1"
     "inputenc"
     "utf8"
     "babel"
     "francais"
     "graphicx"
     "latex2e"
     "art10"
     "article"
     ""
     "pagetitre"
     "cc")))

