(TeX-add-style-hook "serie2-exercices"
 (lambda ()
    (LaTeX-add-labels
     "sec:zone-de-stat"
     "sec:ordre-dintegration"
     "sec:invers-de-proc"
     "sec:constr-dune-serie")
    (TeX-run-style-hooks
     "tabularx"
     "ccicons"
     "scale=2"
     "auto-pst-pdf"
     "off"
     "caption"
     "hypcap"
     "cleveref"
     "hyperref"
     "thmtools"
     "amsthm"
     "amsfonts"
     "amsmath"
     "inputenc"
     "utf8"
     "multirow"
     "tikz"
     "natbib"
     "scrtime"
     ""
     "latex2e"
     "art11"
     "article"
     "francais"
     "english"
     "11pt"
     "pagetitre"
     "cc")))

